###---------eksempla-------------

### Test root endpoint


GET http://localhost:7011/api/v1/

### GET all hotels
GET http://localhost:7011/api/v1/hotel

### Create new hotel
POST http://localhost:7011/api/v1/hotel
Content-Type: application/json

{
    "name": "New test hotel",
    "address": "123 test street"
}
### Get hotel by id
GET http://localhost:7011/api/v1/hotel/1

### Get rooms for hotel by id
GET http://localhost:7011/api/v1/hotel/1/rooms


###Update hotel by ID
PUT http://localhost:7011/api/v1/hotel/2
Content-Type: application/json

{
  "name": "updated hotel",
  "address": "updated add"

}

### DElete dog by ID

DELETE http://localhost:7011/api/v1/hotel/3